version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: realestate
    #    ports:
    #      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    networks:
      - real-estate-network

  backend:
    image: maciejjankowskii/realestate:v1
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/realestate
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: always
    networks:
      - real-estate-network

  frontend:
    image: maciejjankowskii/realestate-front:v1
    container_name: frontend
    ports:
      - "3000:5173"
    depends_on:
      - backend
    restart: always
    networks:
      - real-estate-network

volumes:
  mysql-data:
networks:
  real-estate-network:
    driver: bridge